#!/usr/bin/env python3
"""Turn the executable-neutral Kosmonaut extractions into C++ arrays."""

from __future__ import annotations

import argparse
from pathlib import Path


FILES = (
    ("screens.bin", "screens"),
    ("roads.bin", "roads"),
    ("demo-road.bin", "demo_road"),
    ("tutorial-road.bin", "tutorial_road"),
    ("font.bin", "font"),
    ("font-styles.bin", "font_styles"),
    ("music.bin", "music"),
    ("star-motion.bin", "star_motion"),
    ("star-rng.bin", "star_rng"),
    ("star-path-pointers.bin", "star_path_pointers"),
    ("star-paths.bin", "star_paths"),
    ("level-effects.bin", "level_effects"),
    ("demo-effects.bin", "demo_effects"),
    ("demo-input.bin", "demo_input"),
    ("palette.bin", "palette_registers"),
    ("ship-sprites.bin", "ship_sprites"),
    ("render-masks.bin", "render_masks"),
    ("render-pointers.bin", "render_pointers"),
    ("render-shapes.bin", "render_shapes"),
    ("simulation-tables.bin", "simulation_tables"),
    ("title-scroll.bin", "title_scroll"),
    ("tutorial-scroll.bin", "tutorial_scroll"),
    ("destruction-frames.bin", "destruction_frames"),
)


def array_text(name: str, payload: bytes) -> str:
    lines = []
    for offset in range(0, len(payload), 20):
        row = ", ".join(f"0x{value:02x}" for value in payload[offset : offset + 20])
        lines.append(f"    {row},")
    return (
        f"constexpr std::array<std::uint8_t, {len(payload)}> k_{name}{{{{\n"
        + "\n".join(lines)
        + "\n}};\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    sections = []
    accessors = []
    for filename, name in FILES:
        payload = (args.input / filename).read_bytes()
        sections.append(array_text(name, payload))
        accessors.append(
            f"std::span<const std::uint8_t> kosmonaut_{name}() {{ return k_{name}; }}"
        )

    source = """// Generated by tools/embed_kosmonaut_data.py. Do not edit.
#include "kosmonaut_assets.hpp"

#include <array>

namespace skyroads {
namespace {

""" + "\n".join(sections) + """
} // namespace

""" + "\n".join(accessors) + """

} // namespace skyroads
"""
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(source, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
